<?php

global $routes;

$routes = array (
    'o' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida, saudável, sono, mente, zen, idade, corporal, sensor, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, trueage, true, age, wearables, pulseira, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('home','normalize.min','main'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'home' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida, saudável, sono, mente, zen, idade, corporal, sensor, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, trueage, true, age, wearables, pulseira, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('home','normalize.min','main'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'carenet' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('carenet'),
        'body_class'  => 'home',
        'features'    => array(),
    ),
    'equipe' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('equipe','colorbox'),
        'body_class'  => 'home',
        'features'    => array('modernizr','mCustomScrollbar','colorbox'),
    ),
    'instalar' => array (
        'title'       => 'Carenet no Celular – sua vida mais saudável',
        'description' => 'Monitore suas atividades físicas, seu sono, peso e muito mais. Baixe agora o app grátis e tenha uma vida mais saudável.',
        'keywords'    => 'Carenet, celular, baixe, aplicativo, saúde, atividade física, sono, peso, emagrecimento, mente, zen, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('download-app'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'klip' => array (
        'title'        => 'Klip - Instalação',
        'description'  => 'Monitore suas atividades físicas, seu sono, peso e muito mais. Baixe agora o app grátis e tenha uma vida mais saudável.',
        'keywords'     => 'Carenet, celular, baixe, aplicativo, saúde, atividade física, sono, peso, emagrecimento, mente, zen, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'          => array('faq','equipe'),
        'body_class'   => 'home',
        'features'     => array('modernizr'),
        'meta-refresh' => 'https://s3-sa-east-1.amazonaws.com/carenet-public/klip-windows/Carenet+Klip+Sync.exe',
    ),
    'loja' => array (
        'title'       => 'Loja Carenet',
        'description' => 'Compre seu Klip na Carenet.com.br. Encontre uma variedade de biosensores corporais, acessórios e outros produtos esportivos e compre online.',
        'keywords'    => 'Carenet, biosensor, biossensor, corporal, klip, artigos, esportivos, acessórios, loja, online, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis, health, healthkit, healthbook',
        'css'         => array('loja'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'loja.klip' => array (
        'title'       => 'Loja Carenet',
        'description' => 'Compre seu Klip na Carenet.com.br. Encontre uma variedade de biosensores corporais, acessórios e outros produtos esportivos e compre online.',
        'keywords'    => 'Carenet, biosensor, biossensor, corporal, klip, artigos, esportivos, acessórios, loja, online, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis, health, healthkit, healthbook',
        'css'         => array('loja'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'midia' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('midia','equipe'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'perguntas-frequentes' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('faq','equipe'),
        'body_class'  => 'home',
        'features'    => array('modernizr','colorbox','mCustomScrollbar'),
    ),
    'politica-privacidade' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('equipe'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'termos-de-uso' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('equipe'),
        'body_class'  => 'home',
        'features'    => array('modernizr'),
    ),
    'videos' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array('equipe'),
        'body_class'  => 'home',
        'features'    => array('modernizr','colorbox','mCustomScrollbar'),
    ),
);
