<div style="display:none">
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_21.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_22.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_23.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_24.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_25.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_26.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_27.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_28.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_29.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_30.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_31.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_32.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_33.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_34.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_35.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_36.jpg"></a>
    <a class="galeria-voce-sabia" href="/assets/img/voce-sabia/did_you_know_37.jpg"></a>
</div>

<script type="text/javascript">

    function voceSabia() {
        $('.galeria-voce-sabia').colorbox({
            rel: 'galeria-voce-sabia',
            open:true,
            onComplete: function() {

                $('#cboxClose').css({
                    'top': '5px',
                    'right': '5px'
                });
            }
        });

        return false;
    }

    $(function(){
        $('.galeria-voce-sabia').colorbox({
            rel: 'galeria-voce-sabia',
            onComplete: function() {

                $('#cboxClose').css({
                    'top': '5px',
                    'right': '5px'
                });
            }
        });
    });
</script>