<div id="mediabox">
    <div class="info row">
        <div class="col">
            <img src="../assets/img/carenet/<?= _("porque-carenet_pt.png")?>" alt="<?= _("Porque Carenet? A vida pode ser divertida e fácil") ?>" class="badge">
            <p>
                <?= nl2br(_("Bem-vindo à comunidade CARENET!\nAcreditamos que a vida saudável não\ntem que ser difícil, e vamos ajudá-lo.")) ?>
            </p>
            <ul>
                <li><?= _("Descubra sua idade corporal.") ?></li>
                <li><?= _("Monitore suas atividades.") ?></li>
                <li><?= _("Consolide seus dadoes de saúde.") ?></li>
                <li><?= _("Motive-se e inspire os outros.") ?></li>
            </ul>
            <em><?= _("e muito +!") ?></em>
        </div>
    </div>
</div>


<div class="row pull-up-230">
    <div class="carenet-container">
        <nav id="content-nav">
            <ul>
                <li id="long"><a href="#longevidade"><?= _("Longevidade") ?></a></li>
                <li id="four"><a href="#four-dimensions"><?= _("4 Dimensões") ?></a></li>
                <li id="comu"><a href="#comunidade"><?= _("Comunidade") ?></a></li>
                <li id="desa"><a href="#desafios"><?= _("Desafios") ?></a></li>
                <li id="true"><a href="#trueage"><?= _("Trueage") ?>&reg;</a></li>
            </ul>
        </nav>
    </div>
</div>


<section id="longevidade" class="carenet-container">

    <div id="longevidade-inner">
        <h2><?= _("Longevidade") ?></h2>
        <p>
            <?= nl2br(_("Longevidade, o maior sonho humano está um\npasso mais próximo. O século 20 já nos legou um\npresente fabuloso: mais 30 anos de vida, em média.")) ?>
        </p>

        <p>
            <?= nl2br(_("E estes 30 anos não estão no final do seu ciclo de\nvida, eles formam uma fase nova e empolgante no\nseu meio de vida, durante seu período mais\nprodutivo e ativo.")) ?>
        </p>

        <p>
            <?= nl2br(_("Mas para desfrutar este ciclo de vida\nsuperdimensionado, é necessário tomar conta de\nvocê hoje. Comece a monitorar suas atividades e\nviva mais."))?>
            <a href="#">[<? _("Conheça os biossensores Carenet") ?>]</a>
        </p>
    </div>

</section>


<section id="four-dimensions">
    <div class="carenet-container">
        <div class="row">
            <h2><?= _("4 Dimensões") ?></h2>
            <p class="description">
                <?= nl2br(_("Acompanhe cada dimensão com resultados aplicados em gráficos, onde a partir daí o\nAPP lhe dirá o que melhorar e como você poderá chegar aos seus objetivos de saúde<br />\ncom mais praticidade e objetividade.")) ?>
            </p>
        </div>
    </div>

    <div class="circles">
        <div class="mexer-se"><?= _("Mexer-se") ?></div>
        <div class="center">
            <div class="comer"><?= _("Comer") ?></div>
            <div class="dormir"><?= _("Dormir") ?></div>
        </div>
        <div class="corpo-mente"><?= _("Corpo e Mente") ?></div>
    </div>
    <div class="clear"></div>
    <!-- <hr id="circles-bottom"/> -->

    <div class="info">
        <div class="acompanhe">
            <h3><i>d</i><?= _("Acompanhe") ?></h3>
            <p>
                <?= nl2br(_("Seja por dados que você mesmo insere no\nAPP ou por informações vindas do sensor\nligado ao seu corpo no momento das\natividades, o sistema ajudará você a medir\nsua evolução de uma forma desafiadora e\ndivertida.")) ?>
            </p>
        </div>
        <div class="graficos">
            <h3><i>d</i><?= _("Veja os gráficos") ?></h3>
            <p>
                <?= nl2br(_("Todos os resultados das 4 categorias em\ngráficos de fácil entendimento, que\najudarão você a visualizar o melhor\ncaminho para atingir seus objetivos de\nsaúde.")) ?>
            </p>
        </div>
        <a href="#" class="download-app"><?= _("Baixar App") ?></a>
    </div>
</section>

<section id="comunidade">
    <div class="info">
        <ul>
            <li class="uniao">
                <h3><i>a</i><?= _("O Poder da União") ?></h3>
                <p>
                    <?= _("A Carenet promove a ideia de formar uma comunidade, envolvendo os seus amigos e família, independente da distância e fuso horário.") ?>
                </p>
            </li>
            <li class="familia">
                <h3><i>a</i><?= _("Família") ?></h3>
                <p>
                    <?= _("Use a nossa tecnologia para saber sobre a saúde de seus pais, filhos e cuidar melhor da sua família.") ?>
                </p>
            </li>
            <li class="sharing-health">
                <h3><i>a</i><?= _("Compartilhando Saúde") ?></h3>
                <p>
                    <?= _("As redes socias podem ajudar-nos a atingir o que não poderíamos atingir sozinhos. Compartilhe resultados com seus amigos e atinja suas metas.") ?>
                </p>
            </li>
        </ul>
    </div>
</section>

<section id="desafios">
    <div class="info">
        <h3><?= _("Desafios") ?></h3>
        <p>
            <?= nl2br(_("Os jogos aprimoram a qualidade de nosso cotidiano,\ncombatendo problemas sociais depressão e\nobesidade, além de, claro, ser muito divertido. Você\npoderá desafiar amigos pessoalmente ou virtualmente\nvia APP. Se você quer desafiar alguém au até se auto\ndesafiar, a CARENET vai te ajudar!")) ?>
        </p>
        <ul>
            <li class="desafie-se row">
                <i></i>
                <h4><?= _("Desafie-se") ?></h4>
                <p>
                    <?= nl2br(_("Cada dia pode ser um recomeço. Aceite um novo desafio e\nesforce-se para testar suas habilidades e os seus limites.")) ?>
                </p>
            </li>
            <li class="premios row">
                <i></i>
                <h4><?= _("Atinja Prêmios em grupo") ?></h4>
                <p>
                    <?= nl2br(_("Você pode montar grupos com desafios personalizados, e\ncontar com o senso colaborativo para atingir seus objetivos.")) ?>
                </p>
            </li>
            <li class="competicoes row">
                <i></i>
                <h4><?= _("Competições reais") ?></h4>
                <p>
                    <?= nl2br(_("Procure desafios e competições reais na rede Carenet, onde\na pressão dos grupos o fará atingir metas mais altas.")) ?>
                </p>
            </li>
        </ul>
    </div>
</section>

<section id="trueage">
    <div class="info">
        <h3><?= _("Trueage") ?></h3>
        <div class="detalhes">
            <h5><?= _("Informações detalhadas") ?></h5>
            <p>
                <?= nl2br(_("O TrueAge&reg; gera dados que te\najudam a entender melhor o seu\ncorpo, mostrando como mudanças\ncomportamentais impactam no\nprocesso de envelhecimento e como\nestes dados podem inspira-lo a cuidar\nmelhor da sua saúde.")) ?>
                <a href="#"><?= nl2br(_("Veja como\nfunciona.")) ?></a>
            </p>
        </div>
        <aside>
            <ul>
                <li class="vida-saudavel row">
                    <h4><?= _("Vida Saudável") ?></h4>
                    <i></i>
                </li>
                <li class="historico-familiar row">
                    <h4><?= _("Histórico Familiar") ?></h4>
                    <i></i>
                </li>
                <li class="registros-clinicos row">
                    <h4><?= _("Registros Clínicos") ?></h4>
                    <i></i>
                </li>
                <li class="medicacao row">
                    <h4><?= _("Medicação") ?></h4>
                    <i></i>
                </li>
            </ul>
        </aside>
    </div>

    <div class="bottom-info row">
        <div class="col col-teste">
            <i></i>
            <h3><?= _("Faça o Teste") ?></h3>
            <p>
                <?= nl2br(_("Para descobrir a idade real\ndo seu corpo, baixe o\naplicativo e responda\nalgumas perguntas sobre\nvocê e seu estilo de vida.")) ?>
            </p>
        </div>
        <div class="col col-resultados">
            <i></i>
            <h3><?= _("Veja os Resultados") ?></h3>
            <p>
                <?= nl2br(_("Seus dados serão analisados\npor um algoritmo estatístico,\nque premia atitudes\npositivas e inteligentes de\nsaúde.")) ?>
            </p>
        </div>
        <div class="col col-saudavel">
            <i></i>
            <h3><?= _("Tenha uma vida mais saudável") ?></h3>
            <p>
                <?= nl2br(_("Conhecendo a idade real do\nseu corpo você poderá\nadotar pequenas mudanças\nno seu dia a dia para ter uma\nvida mais longa e saudável.")) ?>
            </p>
        </div>
    </div>

</section>

<div class="clear"></div>

<script>window.jQuery || document.write('<script src="/assets/js/vendor/jquery-1.10.1.min.js"><\/script>')</script>
<script src="/assets/js/plugins.js"></script>
<script src="/assets/js/main.js"></script>

<script>
    var content_nav;

    $(document).ready(function(){
        content_nav = $('#content-nav a');

        $(window).on('scroll', function() {
            //var navHeight = $(window).height() - 100;
            if ($(window).scrollTop() > 600) {
                $('#content-nav').addClass('fixed-top');
            } else {
                $('#content-nav').removeClass('fixed-top');
            }
        });

        content_nav.click(function(evt) {
            $(this).removeClass('selected');
            $(this).addClass('selected');
        });
        $(window).on('load', function() {
            qs=[];
            variaveis=location.search.replace(/\x3F/,"").replace(/\x2B/g," ").split("#");
            if(variaveis!=""){
                for(i=0;i<variaveis.length;i++){
                    nvar=variaveis[i].split("=");
                    qs[nvar[0]]=unescape(nvar[1])
                }
            }
            function QueryString(variavel){
                return qs[variavel];
            }
            var str     = $(location).attr('href');
            var tamanho = str.indexOf('#');
            var menu    = str.substr(tamanho+1,4);

            content_nav.removeClass('selected');
            $('#'+menu+' a').addClass('selected');
        });

    });
</script>
