<div class="container">
    <div class="page-title">
        <h2>NOSSA EQUIPE</h2>
    </div>

    <h3>FUNDADORES</h3>

    <div class="row entry">
        <div class="col row">
            <div class="photo">
                <img src="/assets/img/equipe/immo.png" />
            </div>
            <div class="info">
                <h4>Immo Oliver Paul</h4>
                <p>
                    <?= _("Cidadão suíço, 44 anos, multilíngue, com bacharelado em economia, direito e administração de empresas e mestrado em administração internacional pela...") ?>
                    <a href="#pop-immo" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/pub/immo-oliver-paul/10/527/b34" target="_blank">LinkedIn</a>
                    </li>
                    <li class="twitter">
                        <a href="https://twitter.com/immo_paul" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="photo">
                <img src="/assets/img/equipe/michael.png" />
            </div>
            <div class="info">
                <h4>Dr. Michael Kronenberg</h4>
                <p>
                    <?= _("Cidadão suíço, 36 anos, multilíngue, com
                    doutorado (Ph.D.) em Direito (Governança Corporativa, M&amp;A) pela Universidade de St.
                    Gallen HSG, na Suiça.") ?>
                    <a href="#pop-michael" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/pub/michael-kronenberg/0/87b/85" target="_blank">LinkedIn</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="clear"></div>

    <h3><?= _("ESPECIALISTAS EM SAÚDE") ?></h3>

    <div class="row entry">
        <div class="col">
            <div class="photo">
                <img src="/assets/img/equipe/priscila.png" />
            </div>
            <div class="info">
                <h4>Priscila Camargo</h4>
                <p>
                    <?= _("Formada em Educação Física pela USP, Priscila de F. de Arruda Camargo especializou-se em Prescrição de Exercícios na Saúde, na Doença e no Envelhecimento...") ?>
                     <a href="#pop-priscila" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/in/priscilladearrudacamargo" target="_blank">LinkedIn</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="photo">
                <img src="/assets/img/equipe/portal.png" />
            </div>
            <div class="info">
                <h4><?= _("Portal Sentir Bem") ?></h4>
                <p>
                    <?= _("Idealizado e concebido por Priscilla de F de Arruda Camargo, é editora-chefe do mesmo e está há 7 anos no ar. Com apenas oito meses de vida,
                    o Portal Sentir Bem se...") ?>
                    <a href="#pop-sentirbem" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/sentirbem" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <h3><?= _("PARCERIAS") ?></h3>

    <div class="row entry">
        <div class="col">
            <div class="photo">
                <img src="/assets/img/equipe/sautil.png" />
            </div>
            <div class="info">
                <h4><?= _("Portal Saútil") ?></h4>
                <p>
                    <?= _("O Saútil é uma empresa que presta serviços de saúde para melhorar a qualidade de vida das pessoas.  O nome do site surgiu a partir desse conceito, Saútil = saúde + útil.") ?>
                    <a href="#pop-sautil" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/sautil" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col">
            <div class="photo">
                <img src="/assets/img/equipe/doctors.png" />
            </div>
            <div class="info">
                <h4><?= _("Doctors Way") ?></h4>
                <p>
                    <?= _("A Doctors Way é a maior Rede Profissional Exclusiva para Médicos do Brasil.
                      Criada em 2011, por médicos apaixonados por tecnologia, a rede oferece ferramentas importantes para facilitar o dia a dia dos colegas médicos.") ?>
                    <a href="#pop-doctor" class="more open-modal">[ <?= _("leia mais") ?> ]</a>
                </p>
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/DoctorsWay" target="_blank">Twitter</a>
                    </li>
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/in/doctorsway" target="_blank">LinkedIn</a>
                    </li>
                </ul>
            </div>
            </div>
    </div>



    <div class="clear">-</div>

    <!-- conteúdo dos popups -->
    <div id="inline-content">

        <!-- POPUP -->
        <div id="pop-immo" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/immo.png" />
                <ul class="social">
                    <li class="linkedIn">
                        <a href="http://br.linkedin.com/pub/immo-oliver-paul/10/527/b34" target="_blank">LinkedIn</a>
                    </li>
                    <li class="twitter">
                        <a href="https://twitter.com/immo_paul" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2>IMMO OLIVER PAUL</h2>

                <div class="scrollable">
                    <h3><?= _("Percepção saudável: \"Se você não consegue monitorar, você fez mesmo isso?\"") ?></h3>
                    <p><?= _("Cidadão suíço, 44 anos, multilíngue, com bacharelado em economia, direito e administração de empresas e mestrado em administração internacional pela Universidade de St. Gallen HSG, na Suíça.") ?></p>
                    <p><?= _("Entusiasta por tecnologia e pesquisador da longevidade, Immo é profundamente apaixonado pelo valor e utilidade de novas formas de tecnologia móvel de saúde e por suas consequentes aplicações e benefícios para o consumidor.") ?></p>
                    <p><?= _("Immo trabalhou em consultoria estratégica para empresas de consultoria americanas e europeias. Em 2008 ele aceitou o convite para tornar-se empreendedor em série no Brasil e (co-) fundou várias empresas que impulsionaram o desenvolvimento e distribuição e vendas de produtos de consumo de bem-estar e saúde.") ?></p>
                </div>
            </div>
        </div>

        <!-- POPUP -->
        <div id="pop-michael" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/michael.png" />
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/pub/michael-kronenberg/0/87b/85">LinkedIn</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2>Dr. Michael Kronenberg</h2>

                <div class="scrollable">
                    <h3><?= _("Percepção saudável: \"A minha receita para mais saúde? Tênis geniais, um parque, e grandes amigos\".") ?></h3>
                    <p><?= _("Cidadão suíço, 36 anos, multilíngue, com doutorado (Ph.D.) em Direito (Governança Corporativa, M&A) pela Universidade de St. Gallen HSG, na Suíça. A dissertação recebeu a mais alta distinção (summa cum laude) e ele ganhou o renomado Walther Hug-Preis (2005).") ?></p>
                    <p><?= _("Michael traz com ele ampla experiência internacional em financiamento, fundação, execução operacional e gestão de crescimento de novas startups promissoras, especialmente em mercados emergentes. Durante os últimos seis anos, ele iniciou e geriu três startups no setor de alta tecnologia.") ?></p>
                    <p><?= _("Antes de tornar-se empreendedor em série, Michael foi vice-presidente de estratégias globais e desenvolvimento de novos negócios de uma empresa de logística global. Assim, Michael foi responsável por vários projetos de estratégia corporativa, M&A e de desenvolvimento na China, nos EUA e no Brasil.") ?></p>
                </div>
            </div>
        </div>

        <!-- POPUP -->
        <div id="pop-priscila" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/priscila.png" />
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/in/priscilladearrudacamargo">LinkedIn</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2>Priscila Camargo</h2>

                <div class="scrollable">
                    <p><?= _("Formada em Educação Física pela USP, Priscilla de F. de Arruda Camargo especializou-se em Prescrição de Exercícios na Saúde, na Doença e no Envelhecimento na Faculdade de Medicina da USP (FMUSP) e possui diversos cursos em Nutrição Esportiva. É Consultora em Qualidade de Vida. Colaboradora de revistas no segmento de Qualidade de Vida, como Boa Forma, Guest, Capricho, Corpo a Corpo, com artigos e geração de pautas. Também produziu conteúdo para sites como o da Nike Running, Peugeot, Gendai, China in Box e, recentemente em 2012, para o Instituto Vita e para o site da marca NUTRY, www.euqueroviverbem.com.br.") ?></p>
                    <p><?= _("É uma empresária atenta às oportunidades, capaz de idealizar e implementar atividades diferenciadas na área de informação (conteúdo e comunicação) sobre Saúde e Qualidade de Vida, sempre em busca de novos parceiros de negócios.") ?></p>
                </div>
            </div>
        </div>
        <!-- POPUP -->
        <div id="pop-sentirbem" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/portal.png" />
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/sentirbem" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2><?= _("Portal Sentir Bem") ?></h2>

                <div class="scrollable">
                    <p><?= _("Idealizado e concebido por Priscilla de F. de Arruda Camargo, é editora-chefe do mesmo e está há 7 anos no ar. Com apenas oito meses de vida, o Portal Sentir Bem se tornou parceiro do UOL - o maior provedor de conteúdo do Brasil - nas estações de Ciência e Saúde, Beleza, Estilo de Vida, Boa Forma, Bem-estar, Nutrição e Comportamento. Por três anos tornou-se também, um quadro de saúde e qualidade de vida, nas Rádios Record e USP.") ?></p>
                    <p><?= _("A três últimas novidades do portal – que se tornou um dos canais com conteúdo de mais qualidade da internet do Brasil– são: (1) o Canal Direto com o Ministério da Saúde, com sua chancela (em 2011), (2) parceria inédita e exclusiva com a TV Mídia, empresa responsável pelas mídias dos metrôs e ônibus em 4 estados do Brasil (SP, RJ, DF e João Pessoa), fornecendo dicas de saúde e qualidade de vida (em 2012) e (3) a aquisição do Selo Amigos da Saúde, conferido pelo Ministério da Saúde aos veículos de internet que tem informações de credibilidade em saúde e qualidade de vida.") ?></p>
                    <p><?= _("Além disso, o portal Sentir Bem conta com um time de colunistas de primeira, entre eles o Dr. Claudio Lottenberg, Médico Oftalmologista e Presidente da Sociedade Israelita Albert Einstein, Prof. Dr, Mauricio Simões Abrão, Ginecologista, Dr. Filippo Pedrinola, Endocrinologista, Dr. Nabil Ghorayeb, Cardiologista, entre outros profissionais de diversas áreas e médicos renomados, cada um na sua área de atuação.") ?></p>
                    <p><?= _("O Portal Sentir Bem está sempre em busca de novidades e melhorias em seus serviços e conteúdo a fim de atender cada vez melhor seu internauta, levando até ele informação e, em breve, serviços, de credibilidade e qualidade.") ?></p>
                </div>
            </div>
        </div>

        <!-- POPUP -->
        <div id="pop-sautil" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/sautil.png" />
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/sautil" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2><?= _("Saútil") ?></h2>

                <div class="scrollable">
                    <p><?= _("O Saútil é uma empresa que presta serviços de saúde para melhorar a qualidade de vida das pessoas.  O nome do site surgiu a partir desse conceito, Saútil = saúde + útil.
                        Por meio de orientações de acesso e de saúde (web e telefônicas), proporciona à população o autocuidado prevenindo doenças, gerando o entendimento e informações para lidar melhor com as condições de saúde.") ?></p>

                    <p><?= _("O usuário encontra consultas, exames, atendimento de urgência e emergência, vacinas, qual o procedimento para retirar medicamentos (de baixo e alto custo), além de informações sobre o Programa Dose Certa, Farmácia Popular, Saúde Bucal e notícias sobre saúde atualizadas diariamente.") ?></p>
                    <p><?= _("O conteúdo do site é destinado a orientar o usuário em questões relacionadas à utilização dos recursos da rede pública de saúde, informando sobre a localização das unidades de saúde, além de consolidar e fornecer informações dos procedimentos para sua utilização. O usuário ainda conta com dicas de qualidade de vida, bem estar e as melhores e mais atualizadas notícias de saúde.") ?></P>
                </div>
            </div>
        </div>

        <!-- POPUP -->
        <div id="pop-doctor" class="row popup">
            <div class="col photo">
                <img src="/assets/img/equipe/doctors.png" />
                <ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/in/doctorsway" target="_blank">LinkedIn</a>
                    </li>
                    <li class="twitter">
                        <a href="https://twitter.com/DoctorsWay" target="_blank">Twitter</a>
                    </li>
                </ul>
            </div>

            <div class="col text">

                <h2><?= _("Doctors Way") ?></h2>

                <div class="scrollable">
                    <p><?= _("A Doctors Way é a maior Rede Profissional Exclusiva para Médicos do Brasil.") ?></p>
                    <p><?= _("Criada em 2011, por médicos apaixonados por tecnologia, a rede oferece ferramentas importantes para facilitar o dia a dia dos colegas médicos.") ?></p>

                    <p><?= _("O aplicativo é gratuito e oferece acesso as seguintes ferramentas:") ?></p>

                    <p><?= _("DW Consulta: ferramenta de perguntas e respostas, de médicos para médicos. DW TV: Aulas em video para você assistir a qualquer hora e lugar.
                        Calculadoras Médicas: Índice de Massa Corpórea , Cálculo da Função Renal , LDL Colesterol , Escala de Glasgow e mais. Centro de Estudos: Artigos nacionais e internacionais, comentados por especialistas de cada área, divididos por temas em medicina, com atualização diária e semanal.  Mural: convide colegas participantes da Doctors Way para fazerem parte dos seus contatos e monte sua própria rede.") ?></p>
                    <p><?= _("Perfil Profissional: seu perfil profissional disponível para toda comunidade médica.") ?></p>
                    <p><?= _("Notícias: notícias em medicina, de fontes nacionais e internacionais, atualizadas em tempo real no seu IPhone.") ?></p>

                </div>
            </div>
        </div>


        <div class="clear"></div>

    </div>


</div>

<script type="text/javascript">
    $(function(){
        $(".open-modal").colorbox({
            inline:true,
            width:"960px",
            scrolling: false,
            fixed: true
        });

        $(document).bind('cbox_complete', function(){
            $(".scrollable").mCustomScrollbar({
                advanced:{
                    updateOnContentResize: true
                }
            });
        });
    });
</script>
