<div id="mediabox"></div>

<div class="download-app-container">
    <div class="box-top"></div>
    <div class="intro">
        <h1><?= _("Para todos os sistemas, para todas as pessoas.") ?></h1>
        <p>
            <?= _("O APP Carenet Longevity recebe todos os dados que você mesmo
            insere no sistema, ou aqueles através do seu KLIP
            Carenet, exibindo todas as informações em gráficos
            simples e atrativos que vão auxiliar você à atingir
            seus objetivos de saúde. Coloque seu corpo para
            funcionar, coma bem, durma bem, e deixe sua mente
            e seu corpo em plena harmonia. Baixe já!") ?>
        </p>
        <div class="clear"></div>
    </div>

    <div class="lojas row">
        <a href="javascript:alert('Em breve');" class="app-store"><?= _("App Store") ?></a>
        <a href="javascript:alert('Em breve');" class="google-play"><?= _("Google Play") ?></a>
    </div>

    <div class="row platforms">

        <div class="ios">
            <div class="info">
                <span><?= _("apple") ?></span>
                <strong><?= _("IOS") ?></strong>
                <small><?= _("iPAD") ?> <br/><?= _("iPhone") ?></small>
                <a href="https://itunes.apple.com/us/app/carenet-longevity/id863030381?mt=8" class="download-now"><?= _("Baixar") ?></a>
            </div>
        </div>

        <div class="android">
            <div class="info">
                <span><?= _("google") ?></span>
                <strong><?= _("android") ?></strong>
                <small><?= _("Tablets") ?><br/><?= _("Celulares") ?></small>
                <a href="javascript:alert('Em breve');" class="download-now"><?= _("Baixar") ?></a>
            </div>
        </div>

    </div>
</div>
<script src="/assets/js/plugins.js"></script>
<script src="/assets/js/main.js"></script>
