<div class="container">
    <div class="page-title">
        <h2><?= _("MÍDIA") ?> / <?= _("PRESS KIT") ?></h2>
    </div>
    <div class="row">
        <div class="intro">
            <div class="text">
                <h1><?= _("Não acredite apenas em nossa palavra.") ?></h1>
                <span><?= _("Aqui você pode ver alguns veículos da imprensa onde CARENET foi citado.") ?></span>
            </div>
            <div class="download">
                <a href="/press/Press.pdf" target="_blank"><?= _("Download Press Kit") ?></a>
            </div>
        </div>
    </div>

    <div class="row">
        <ul class="midia">
            <li>
                <div class="logo">
                    <img src="/assets/img/midia/r7.jpg">
                </div>
                <div>
                    <p>"<?= _("Sensores corporais podem prolongar vida dos
                    usuários e aumentar a transparência na hora da consulta.") ?>"</p>
                    <span>21/02/2014</span>
                </div>
            </li>
            <li>
                <div class="logo">
                    <img src="/assets/img/midia/acritica.jpg">
                </div>
                <div>
                    <p>"<?= _("Sensores corporais prometem monitorar a saúde 24 horas por dia.") ?>"</p>
                    <span>27/02/2014</span>
                </div>
            </li>
            <li>
                <div class="logo">
                    <img src="/assets/img/midia/tibahia.jpg">
                </div>
                <div>
                    <p>"<?= _("Sensores corporais estarão à venda no Brasil em janeiro.") ?>"</p>
                    <span>20/01/2014</span>
                </div>
            </li>
            <li>
                <div class="logo">
                    <img src="/assets/img/midia/sbot-am.jpg">
                </div>
                <div>
                    <p>"<?= _("Sensores corporais prometem monitorar a saúde 24 horas por dia.") ?></p>
                </div>
            </li>
        </ul>
    </div>
</div>
