<div class="container">
<div class="page-title">
    <h2><?= _("POLITICA DE PRIVACIDADE") ?></h2>
</div>

<div class="content">
    <div style="margin-left: 30px; margin-right: 30px">
    <p><?= _("A Carenet leva a segurança das informações muito a sério. Independentemente de ser um Usuário ou um simples visitante de nossa página virtual ou aplicativo, nós tratamos todas as informações que recebemos e/ou armazenamos como Informações Pessoais. Abaixo, expomos nossas premissas no manuseio das informações.") ?></p>
    <ol>
        <li><?= _("A Carenet somente coletará e/ou armazenará as Informações Pessoais identificáveis do Usuário se este as fornecer voluntariamente; entende-se como Informações Pessoais identificáveis aquelas em que é possível saber qual o Usuário que forneceu a informação.") ?></li>
        <li><?= _("A Carenet não poderá divulgar Informações Pessoais do Usuário a terceiros, de forma identificada, sem o seu consentimento prévio, exceto quando for exigido por lei, determinado pelo Poder Judiciário ou outro órgão competente para tanto, ou se exigido pelas circunstâncias, dentre outros.") ?></li>
        <li><?= _("A Carenet poderá utilizar Informações Pessoais do Usuário, de forma não identificada e agregada a informações de outros Usuários, oriundas do perfil do usuário e/ou outras informações de uso da Plataforma Carenet, para, incluindo, mas não se limitando a, gerar dados e levantamentos estatísticos, bem como para gerar novas funcionalidades e conteúdos para a Plataforma Carenet; a Carenet poderá, ainda, realizar análises estatísticas sobre o comportamento do usuário, de forma agregada e não identificável, a fim de medir o interesse e o uso de diversas áreas e características da Plataforma Carenet.") ?></li>
        <li><?= _("Caso um Usuário queira realizar a exclusão de seus registros, a Carenet, mediante solicitação expressa e escrita, poderá excluir da Plataforma Carenet o nome de usuário e Informações Pessoais identificáveis (ou seja, a vinculação entre suas informações e seus dados de Usuário), mas manterá as informações fornecidas para fins de histórico e base estatística, sem qualquer tipo de identificação.") ?></li>
        <li><?= _("Empresas direta ou indiretamente ligadas à Carenet, por meio de laços societários ou semelhança de sócios, não são considerados terceiros para efeitos de cessão de informações.") ?></li>
        <li><?= _("A Carenet poderá ceder as informações relativas aos Usuários da Plataforma Carenet em caso de reorganização societária ou cessão de ativos, independentemente de aviso prévio aos usuários.") ?></li>
    </ol>
    <p><?= _("A Plataforma Carenet usa as tecnologias disponíveis para aumentar a privacidade dos dados e ajudar a prevenir a perda, mau uso ou alteração das informações sob a gerência da Carenet; estas tecnologias, entretanto, podem, eventualmente, não garantir ou proteger a total privacidade das informações voluntariamente inseridas pelo Usuário na Plataforma Carenet, não podendo a Carenet ser responsabilizada por perdas, extravio, roubo, furto, ou qualquer outra forma de obtenção ou divulgação de informação quando ela não for voluntariamente realizada pela Carenet.") ?></p>
    </div>
</div>
<div class="clear">-</div>
</div>