<div class="container">
    <div class="page-title">
        <h2><?= _("TERMOS DE USO") ?></h2>
    </div>

    <div class="content">
        <div style="margin-left: 30px; margin-right: 30px">
        <p><?= _("Ao acessar e/ou utilizar este site e seus aplicativos (“Plataforma Carenet”), o visitante e/ou usuário cadastrado (em conjunto definidos como “Usuário”) aceita(m) e concorda(m) que:") ?></p>
        <ol>
            <li><?= _("O Usuário é o único e exclusivo titular e responsável pela clareza, objetividade e precisão das informações pessoais que cadastrar voluntariamente no software/sistema (“Informações Pessoais”);") ?></li>
            <li><?= _("A Carenet utilizará as Informações Pessoais do Usuário para processar e lhe fornecer informações personalizadas sobre saúde e bem estar (“Informações Personalizadas”), por meio da Plataforma Carenet;") ?></li>
            <li><?= _("A Carenet também utilizará as Informações Pessoais dos seus Usuários, de forma não identificada e agregada a informações de outros Usuários para, incluindo, mas não se limitando a, gerar dados e levantamentos estatísticos, bem como para gerar novas funcionalidades e conteúdos para a Plataforma Carenet, sem, contudo, identificar o Usuário que as forneceu; a Carenet poderá, ainda, realizar análises estatísticas sobre o comportamento do usuário, de forma agregada e não identificável, a fim de medir o interesse e o uso de diversas áreas e características da Plataforma Carenet;") ?></li>
            <li><?= _("A Carenet não poderá divulgar Informações Pessoais identificáveis do Usuário a terceiros, sem o seu consentimento prévio, salvo se assim for exigido por lei ou determinação judicial, ou demais casos previstos em sua Política de Privacidade;") ?></li>
            <li><?= _("A Carenet adota mecanismos e ferramentas para aumentar a privacidade dos dados e ajudar a prevenir a perda, mau uso ou alteração das informações sob seu controle, garantindo a segurança de acesso até o limite daqueles;") ?></li>
            <li><?= _("A Carenet não será responsável pelas informações que o Usuário compartilhar com outros usuários, com grupos de Usuários do software e nem por aquelas que o usuário compartilhar por meio de vínculos com outras redes sociais;") ?></li>
            <li><?= _("A Plataforma Carenet foi projetado para gerar Informações Personalizadas a partir de dados fornecidos pelos usuários, tendo, portanto, finalidade meramente educacional, de orientação e estatística;") ?></li>
            <li><?= _("A Plataforma Carenet não pode e não deve ser entendido como um diagnóstico médico ou como um substituto a consultas com um profissional da medicina; as Informações Personalizadas, igualmente, não poderão ser utilizadas para diagnosticar ou tratar um problema de saúde ou doença, devendo o Usuário procurar um profissional de sua confiança caso busque uma avaliação precisa sobre sua condição;") ?></li>
            <li><?= _("Para fornecer informações personalizadas sobre saúde e bem estar, a Plataforma Carenet leva em consideração dados populacionais e padrões estatísticos, além das Informações Pessoais do Usuário, de modo que, pode apresentar resultados “falsos positivos” e/ou “falsos negativos” (conforme conceitos de probabilidade);") ?></li>
            <li><?= _("A Carente aconselha o Usuário a consultar regularmente, e sempre que necessário, seu médico de confiança;") ?></li>
            <li><?= _("A utilização da Plataforma Carenet está sujeita aos termos e condições disponíveis em www.carenet.com.br, ficando o usuário obrigado a cumpri-las; bem como a termos e condições de parceiros de negócio da Carenet, quando aplicável e assim notificado ao Usuário;") ?></li>
            <li><?= _("Leu e compreendeu os Termos de Uso e concorda em se sujeitar às suas condições;") ?></li>
        </ol>

        <p><?= _("É pessoa capaz, na acepção jurídica do termo.") ?></p>
        </div>
    </div>

    <div class="clear">-</div>
</div>
