<div class="container">
    <div class="page-title">
        <h2><? _("VÍDEOS") ?></h2>
    </div>

    <div class="row entry">
        <div class="col row">
            <div class="photo">
                <br/><br/>
                <object width="150" height="84.375">
                    <param name="movie" value="https://www.youtube.com/v/_dYYT3_VQZw?version=3"/>
                    <param name="allowFullScreen" value="true"/>
                    <param name="allowScriptAccess" value="always"/>
                    <embed src="https://www.youtube.com/v/_dYYT3_VQZw?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="150" height="84.375"></embed>
                </object>
            </div>
            <div class="info">
                <h4><? _("Saiba mais sobre o KLIP") ?></h4>
                <p>
                    <? _("Use o KLIP com o App Carenet e saiba como andam seus esforços para obter mais saúde e qualidade de vida.") ?>
                </p>
            </div>
        </div>
        <div class="col">
            <div class="photo">
                <br/><br/>
                <object width="150" height="84.375">
                    <param name="movie" value="https://www.youtube.com/v/sDEbOScR-Jg?version=3"/>
                    <param name="allowFullScreen" value="true"/>
                    <param name="allowScriptAccess" value="always"/>
                    <embed src="https://www.youtube.com/v/sDEbOScR-Jg?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="150" height="84.375"></embed>
                </object>
            </div>
            <div class="info">
                <h4><? _("Como usar seu KLIP") ?></h4>
                <p>
                    <? _("Saiba como ativar e sincronizar o seu KLIP e monitore mais de 30 indicadores das suas atividades diárias.") ?>
                </p>
                <!--<ul class="social">
                    <li class="linkedIn">
                        <a href="https://br.linkedin.com/pub/michael-kronenberg/0/87b/85" target="_blank">LinkedIn</a>
                    </li>
                    <li class="email">
                        <a href="#">email</a>
                    </li>
                </ul>!-->
            </div>
        </div>
    </div>

    <div class="clear">-</div>
</div>